# Generated by Django 3.0.7 on 2020-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200620_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подтвержденный аккаунт'),
        ),
    ]
