# Generated by Django 3.0.7 on 2020-06-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200621_0124'),
        ('posts', '0006_auto_20200621_0124'),
        ('auth', '0011_update_proxy_permissions'),
        ('authtoken', '0003_auto_20200621_0124'),
        ('account', '0008_auto_20200621_0121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
